Better error messaging when the JT can't be found

diff --git a/bin/brisk b/bin/brisk
--- a/bin/brisk
+++ b/bin/brisk
@@ -33,6 +33,9 @@ case "$1" in
             if [ "x$HADOOP_CMD" != "x" ]; then
                 HADOOP_JT="-D brisk.job.tracker=$JOBTRACKER"
             fi
+        else
+            echo "Unable to start job: jobtracker not found"
+            exit 2
         fi
 
         #special case for jar
@@ -58,7 +61,10 @@ case "$1" in
 
         JOBTRACKER=`$BIN/brisktool jobtracker`;
         if [ "x$JOBTRACKER" != "x" ]; then
-        HIVE_OPTS="$HIVE_OPTS -hiveconf brisk.job.tracker=$JOBTRACKER"
+            HIVE_OPTS="$HIVE_OPTS -hiveconf brisk.job.tracker=$JOBTRACKER"
+        else
+            echo "Unable to start job: jobtracker not found"
+            exit 2
         fi
 
         export HIVE_OPTS="$HIVE_OPTS -hiveconf hive.log.dir=$BRISK_LOG_ROOT/hive -hiveconf brisk.home=$BRISK_HOME"
