Work for BRISK-164, auto detect job tracker

diff --git a/bin/brisk b/bin/brisk
--- a/bin/brisk
+++ b/bin/brisk
@@ -15,6 +15,19 @@ fi
 
 BIN=`dirname $0`
 
+update_jobtracker()
+{
+    JOBTRACKER=`$BIN/brisktool jobtracker`;
+    
+    if [ "x$JOBTRACKER" = "x" ]; then
+	echo "error finding jobtracker address"
+	exit 1
+    else
+	sed -e "s/<!--brisk jobtracker-->/$JOBTRACKER/g" $HADOOP_HOME/conf/mapred-site.xml.brisk > $HADOOP_HOME/conf/mapred-site.xml
+    fi
+}
+
+
 if [ "x$1" = "xcassandra" ]; then
     shift
     $CASSANDRA_BIN/cassandra $* -Djava.library.path=$JAVA_LIBRARY_PATH
@@ -23,7 +36,10 @@ fi
 
 if [ "x$1" = "xhadoop" ]; then
     shift
-    $HADOOP_BIN/hadoop $*
+
+    update_jobtracker
+
+    $HADOOP_BIN/hadoop $*    
     exit $?
 fi
 
@@ -33,6 +49,8 @@ if [ "x$1" = "xhive" ]; then
     #we need to remove the conflicting antlr jar
     export CLASSPATH=`echo $CLASSPATH | sed -E "s/antlr|slf4j/dne/g"`
     export HADOOP_CLASSPATH=$CLASSPATH
+
+    update_jobtracker
     
     $HIVE_BIN/hive -hiveconf hive.log.dir=$BRISK_LOG_ROOT/hive -hiveconf brisk.home=$BRISK_HOME $*
     exit $?
